name: ci

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  YARN_CACHE_DIR: .cache/yarn

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions@checkout@v2

      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dependencies
        uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_DIR}
          key: ${{ runner.os }}-yarn-cache-v1
        run: yarn --frozen-lockfile --non-interactive

      - name: run lint
        run: yarn run lint
        working-directory: ./packages/v-confirm
